version: '3.7'
services:
  discoveryservice:
    build:
      context: ../discoveryservice
      dockerfile: Dockerfile
    image: 'discoveryservice:latest'
    networks:
      - front
    ports:
      - 8761:8761
  gatewayservice:
    build:
      context: ../gatewayservice
      dockerfile: Dockerfile
    image: 'gatewayservice:latest'
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"profiles": {"active": "docker"}}}'
    networks:
      - front
    ports:
      - 8080:8080
    depends_on:
      - discoveryservice
  tb:
    build:
      context: ../tb
      dockerfile: Dockerfile
    environment:
      REACT_NATIVE_PACKAGER_HOSTNAME: "192.168.1.104"
    networks:
      - front
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
networks:
  front:
    driver: bridge